### ISSUE TITLE
disable search if it is not supported

### ISSUE THREAD

**Issue by juliuste** [derhuerst/casket#10]
When trying to use the search on non-mac-OS-system, casket crashes instead of showing a notification or something similar.

**Comment by derhuerst** [comment]
How does it crash?

**Comment by juliuste** [comment]
```sh
Error: not implemented
    at Readable._read (_stream_readable.js:471:22)
    at Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by derhuerst** [comment]
I've published `node-spotlight@0.1.3`, which closes the (fallback) stream properly. Nevertheless, `casket` should use the `support` flag to decide wether to show the search form.

**Comment by derhuerst** [comment]
fixed by c8c2bd5.

**Comment by juliuste** [comment]
Would you mind publishing the fixed version to npm? 🙂

**Comment by derhuerst** [comment]
`+ casket@1.6.2`
